### Verbo GET – listar 1
GET http://localhost:8000/funcionario/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey


### Verbo POST – adicionar
POST http://localhost:8000/funcionario/ HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome" : "Rodrigo Lorenzetti - Funcionario",
    "cpf" : "12345670909",
    "telefone" : "49999999999",
    "senha" : "1234",
    "matricula" : "123456",
    "grupo" : 2
}

### Verbo PUT – atualiza
PUT http://localhost:8000/funcionario/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey
content-type: application/json

{
    "nome" : "Rodrigo Lorenzetti Cordova - Funcionário",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "senha" : "abc",
    "matricula" : "54321",
    "grupo" : 2
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/funcionario/1 HTTP/1.1
x-token: abcBolinhasToken
x-key: abcBolinhasKey