### Verbo GET – listar
GET http://localhost:8000/produto/0 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/produto/4 HTTP/1.1
content-type: application/json

{
    "nome" : "Pastel",
    "descricao" : "Pastel de frango",
    "foto" : "",
    "valor" : 12.50
}

### Verbo PUT – atualiza
PUT http://localhost:8000/produto/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Suco de Laranja",
    "descricao" : "Gostoso suco de laranja",
    "foto" : "",
    "valor" : 10.00
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/produto/3 HTTP/1.1