### Verbo GET – listar
GET http://localhost:8000/cliente/0 HTTP/1.1

### Verbo POST – adicionar
POST http://localhost:8000/cliente/4 HTTP/1.1
content-type: application/json

{
    "nome" : "Bolinhas dos Testes",
    "cpf" : "12345678909",
    "telefone" : "49898989",
    "senha" : "abc",
    "compra_fiado" : 0,
    "dia_fiado" : 0
}

### Verbo PUT – atualiza
PUT http://localhost:8000/cliente/2 HTTP/1.1
content-type: application/json

{
    "nome" : "Rodrigo Lorenzetti",
    "cpf" : "10210210225",
    "telefone" : "49984224677",
    "senha" : "123456",
    "compra_fiado" : 1,
    "dia_fiado" : 26
}

### Verbo DELETE - excluir
DELETE http://localhost:8000/cliente/3 HTTP/1.1